### ISSUE TITLE
Unclear reference to previous items

### ISSUE THREAD

**Issue by llueg** [ulissigroup/F22-06-325#4]
https://github.com/ulissigroup/F22-06-325/blob/555a13bbb5b78d4a64a2c4262a8895000301c34d/f22-06-325/notes/review_odes.md?plain=1#L230

Maybe this is just me, but what items is this sentence referring to? Might be good to reiterate them.

Also, in second sentence, it should be 'Will it ...' instead of 'It will...' .

**Comment by llueg** [comment]
@zulissi Should we open issues for these kinds of questions or discuss on slack first?

**Comment by zulissi** [comment]
Addressed with a11f61953472d311991fe33058a86d0b9b2dcf3b
