### ISSUE TITLE
Issue on page /software.html

### ISSUE THREAD

**Issue by apotcher** [ulissigroup/F22-06-325#8]
I was hoping you could go into more detail on how to install the linux workspace on a window's laptop, that would be something I am interested in using this and learning it!

Thanks

**Comment by apotcher** [comment]
This is Alexander Potchernikov, by the way.

**Comment by zulissi** [comment]
Let me know if it's clear using 69f1e2b918a5089f757eb1e406cc4624b63f53c5 (should update on the website 5-10 min after it's changed on github)
